// Widths
localparam
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_EVT_LTC         = 48,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_START_ADDR      = 12,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_STOP_ADDR       = 12,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_TRIG_SRC        = 2,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_CNST_RUN        = 1,
  L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_PRE_CONF        = 5;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_WVB_HDR_BUNDLE_0_EVT_LTC         = 0,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_0_START_ADDR      = 48,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_0_STOP_ADDR       = 60,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_0_TRIG_SRC        = 72,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_0_CNST_RUN        = 74,
  L_START_POS_MDOM_WVB_HDR_BUNDLE_0_PRE_CONF        = 75;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_0_EVT_LTC         = 47,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_0_START_ADDR      = 59,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_0_STOP_ADDR       = 71,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_0_TRIG_SRC        = 73,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_0_CNST_RUN        = 74,
  L_STOP_POS_MDOM_WVB_HDR_BUNDLE_0_PRE_CONF        = 79;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_WVB_HDR_BUNDLE_0_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_WVB_HDR_BUNDLE_0 = 80;
