// Widths
localparam
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_CNST_CONF       = 12,
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_TEST_CONF       = 12,
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_POST_CONF       = 8,
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_PRE_CONF        = 5,
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_ARM             = 1,
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_TRIG_MODE       = 1,
  L_WIDTH_MDOM_WVB_CONF_BUNDLE_CNST_RUN        = 1;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_WVB_CONF_BUNDLE_CNST_CONF       = 0,
  L_START_POS_MDOM_WVB_CONF_BUNDLE_TEST_CONF       = 12,
  L_START_POS_MDOM_WVB_CONF_BUNDLE_POST_CONF       = 24,
  L_START_POS_MDOM_WVB_CONF_BUNDLE_PRE_CONF        = 32,
  L_START_POS_MDOM_WVB_CONF_BUNDLE_ARM             = 37,
  L_START_POS_MDOM_WVB_CONF_BUNDLE_TRIG_MODE       = 38,
  L_START_POS_MDOM_WVB_CONF_BUNDLE_CNST_RUN        = 39;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_CNST_CONF       = 11,
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_TEST_CONF       = 23,
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_POST_CONF       = 31,
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_PRE_CONF        = 36,
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_ARM             = 37,
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_TRIG_MODE       = 38,
  L_STOP_POS_MDOM_WVB_CONF_BUNDLE_CNST_RUN        = 39;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_WVB_CONF_BUNDLE_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_WVB_CONF_BUNDLE = 40;
