// Widths
localparam
  L_WIDTH_MDOM_BSUM_BUNDLE_PAUSE           = 1,
  L_WIDTH_MDOM_BSUM_BUNDLE_PAUSE_OVERRIDE  = 1,
  L_WIDTH_MDOM_BSUM_BUNDLE_SUM_LEN_SEL     = 3,
  L_WIDTH_MDOM_BSUM_BUNDLE_PAUSE_LEN       = 16,
  L_WIDTH_MDOM_BSUM_BUNDLE_DEV_LOW         = 12,
  L_WIDTH_MDOM_BSUM_BUNDLE_DEV_HIGH        = 12;

// Start position = Previous start + Width
localparam 
  L_START_POS_MDOM_BSUM_BUNDLE_PAUSE           = 0,
  L_START_POS_MDOM_BSUM_BUNDLE_PAUSE_OVERRIDE  = 1,
  L_START_POS_MDOM_BSUM_BUNDLE_SUM_LEN_SEL     = 2,
  L_START_POS_MDOM_BSUM_BUNDLE_PAUSE_LEN       = 5,
  L_START_POS_MDOM_BSUM_BUNDLE_DEV_LOW         = 21,
  L_START_POS_MDOM_BSUM_BUNDLE_DEV_HIGH        = 33;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_MDOM_BSUM_BUNDLE_PAUSE           = 0,
  L_STOP_POS_MDOM_BSUM_BUNDLE_PAUSE_OVERRIDE  = 1,
  L_STOP_POS_MDOM_BSUM_BUNDLE_SUM_LEN_SEL     = 4,
  L_STOP_POS_MDOM_BSUM_BUNDLE_PAUSE_LEN       = 20,
  L_STOP_POS_MDOM_BSUM_BUNDLE_DEV_LOW         = 32,
  L_STOP_POS_MDOM_BSUM_BUNDLE_DEV_HIGH        = 44;

// Zero pad width and bundle width
localparam L_WIDTH_MDOM_BSUM_BUNDLE_ZERO_PAD = 0;
localparam L_WIDTH_MDOM_BSUM_BUNDLE = 45;
